name: DuplicateDetect
version: '${project.version}'
main: me.nt.checkitemduplicate.DuplicateDetect
api-version: 1.12

commands:
  dd:
    description: Item Duplicate Detect plugin
    usage: /<command>
    permission: DuplicateDetect.command.basic
